name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 17.1.1
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @google/semantic-release-replace-plugin
      - name: Notify JuliaRegistrator of new release
        uses: peter-evans/commit-comment@v1
        with:
          body: '@JuliaRegistrator register branch=master'
